#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the navbar)
name: Alex on Software

# Your site's title (e.g., Ben's Awesome Site, The GitHub Blog, etc.), used as part of the title tag like Home | Ben's Awesome Site.
title: Alex on Software

# Link to avatar in the navbar (/assets/images/avatar.png). Leave empty if no logo desired.
avatar: assets/images/alex.jpg

# A short description (e.g., A blog dedicated to reviewing cat gifs), used as part of the title tag like Ben's Awesome Site | A blog dedicated to reviewing cat gifs instead of Ben's Awesome Site | Long description about a blog dedicated to reviewing cat gifs that would be used when page.title is not defined.
tagline: Alex on Software

# A longer description used for the description meta tag. Also used as fallback for pages that don't provide their own description, and also as part of the page's title tag if neither page.title nor site.tagline has been defined.
description: Alexs personal blog

domain: alex0x08.github.io
# The full URL to your site. Note: site.github.url will be used by default.
url: https://alex0x08.github.io/
#https://andrewhwanpark.github.io/minimal-bootstrap-blog/


repository: alex0x08/alex0x08.github.io



# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: /

# global author information
author: alex0x08

# URL to a site-wide logo (e.g., /assets/your-company-logo.png)
logo: /assets/images/alex.jpg

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: GTM-PKWJ5RV

permalink: /:year/:month/:day/:title/

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: alex0x08


# Includes an icon in the footer for each username you enter
footer-links:
  email: alex3.145@gmail.com
  facebook:
  github: alex0x08/blog
  instagram: alex0x08
  linkedin: alex0x08
  rss: # just type anything here for a working RSS icon
#  twitter: andrewhwanpark

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
#  - jekyll-font-awesome-sass

#font-awesome:
#  assets: true
